this.ola2 = 'Legal';
//this é uma forma de importar
/*  O ARQUIVO INDEX VOCE ELE PODE Inclusive 
SER UMA FORMA ÚNICA DE DE VOCE ACESSAR VÁRIOS IMPORTS
DE OUTROS ARQUIVOS 
- ENTÃO VOCE PODE DENTRO DO ARQUIVO INDEX;
- REFERENCIAS OUTROS ARQUIVOS E RETORNAR UM OBJETO
-  QUE SERIA A JUNÇÃO DE TODOS OS ARQUIVOS DE UMA DETERMINADA PASTA 
- DA MINHA ESCOLHA QUE VOCE CRIOU NO SISTEMA
*/
